
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Point;


import javax.swing.ComboBoxModel;


@SuppressWarnings("serial")
public class farmsInventory extends javax.swing.JFrame {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BaseBoardPanel;
    private java.awt.Label Title;
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DelButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JLabel LabelCredits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable Tablelist;
    private javax.swing.JTextField txtItemcode;
    private java.awt.Label Descriptionlabel;
    private java.awt.Label labelProduct;
    private java.awt.Label labelQTY;
    private java.awt.Label labelITEMCODE;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form frameCRUD
     */
    public farmsInventory() {
    	setResizable(false);
    	setLocation(new Point(100, 100));
        initComponents();
    }
    //FILE HANDLING CONCEPT HERE
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        BaseBoardPanel = new javax.swing.JPanel();
        labelProduct = new java.awt.Label();
        txtItemcode = new javax.swing.JTextField();
        labelQTY = new java.awt.Label();
        labelITEMCODE = new java.awt.Label();
        ComboBox = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        AddButton = new javax.swing.JButton();
        DelButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        LabelCredits = new javax.swing.JLabel();
        Title = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablelist = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Descriptionlabel = new java.awt.Label();
        ProgressBar = new javax.swing.JProgressBar();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(50, 50));

        BaseBoardPanel.setBackground(new java.awt.Color(113, 161, 220));

        labelProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelProduct.setForeground(new java.awt.Color(242, 247, 247));
        labelProduct.setText("Products");

        txtItemcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	txtItemcodeActionPerformed(evt);
            }
        });

        labelQTY.setForeground(new java.awt.Color(242, 247, 247));
        labelQTY.setText("Quantity");

        labelITEMCODE.setForeground(new java.awt.Color(242, 247, 247));
        labelITEMCODE.setText("ItemCode");

        ComboBox.setEditable(true);
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice", "Corn", "SugarCane", "Potato" }));
        ComboBox.setName(""); // NOI18N
        ComboBox.setVerifyInputWhenFocusTarget(false);
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(116, 222, 219));
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        DelButton.setBackground(new java.awt.Color(116, 222, 219));
        DelButton.setText("Delete");
        DelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDelActionPerformed(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(116, 222, 219));
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(116, 222, 219));
        SubmitButton.setText("Submit");

        LabelCredits.setForeground(new java.awt.Color(255, 255, 255));
        LabelCredits.setText("@xilerjohn");

        javax.swing.GroupLayout BaseBoardPanelLayout = new javax.swing.GroupLayout(BaseBoardPanel);
        BaseBoardPanelLayout.setHorizontalGroup(
        	BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        			.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(LabelCredits)
        						.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING, false)
        							.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        								.addComponent(labelProduct, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        								.addComponent(ComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        								.addComponent(labelQTY, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        							.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        								.addComponent(labelITEMCODE, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(txtItemcode, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
        							.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        								.addComponent(AddButton, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(DelButton, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))))
        				.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        					.addGap(58)
        					.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(SubmitButton, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        						.addComponent(EditButton, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        BaseBoardPanelLayout.setVerticalGroup(
        	BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(BaseBoardPanelLayout.createSequentialGroup()
        			.addGap(49)
        			.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(labelProduct, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(28)
        			.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(labelQTY, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtItemcode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(labelITEMCODE, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addGroup(BaseBoardPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(AddButton)
        				.addComponent(DelButton))
        			.addGap(32)
        			.addComponent(EditButton)
        			.addGap(18)
        			.addComponent(SubmitButton)
        			.addPreferredGap(ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
        			.addComponent(LabelCredits)
        			.addGap(22))
        );
        BaseBoardPanel.setLayout(BaseBoardPanelLayout);

        ComboBox.getAccessibleContext().setAccessibleName("");
        ComboBox.getAccessibleContext().setAccessibleDescription("");
        jSpinner1.getAccessibleContext().setAccessibleDescription("");

        Title.setAlignment(java.awt.Label.CENTER);
        Title.setBackground(new java.awt.Color(232, 237, 242));
        Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Title.setText("Farmers Product Inventory System");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        Tablelist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tablelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Products", "Quantity", "ITEM CODE"
            }
        ));
        Tablelist.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(Tablelist);
        Tablelist.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Tablelist.getColumnModel().getColumnCount() > 0) {
            Tablelist.getColumnModel().getColumn(0).setHeaderValue("Products");
            Tablelist.getColumnModel().getColumn(1).setHeaderValue("Quantity");
            Tablelist.getColumnModel().getColumn(2).setHeaderValue("ITEM CODE");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        Descriptionlabel.setText("Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(BaseBoardPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(Descriptionlabel, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        					.addGap(0, 416, Short.MAX_VALUE))
        				.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        				.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        				.addComponent(ProgressBar, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        			.addContainerGap())
        		.addComponent(Title, GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(Title, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addGap(1)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(Descriptionlabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(5)
        					.addComponent(ProgressBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addComponent(BaseBoardPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      //this is delete button.
//        jSpinner1.set("");
//        jComboBox1.set("");
//        jTextField3.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ComboBoxModel<String> products = ComboBox.getModel();
    String ItemCode = txtItemcode.getText();
    try {
    	
    }catch(Exception er) {
    	
    }
    
               
    }//GEN-LAST:event_jButton1ActionPerformed	
}


